[WIP] As a user, I can log in
hoangmirs/go-scraper pull request #27
Opened 2021-01-18 12:49 UTC by hoangmirs

https://github.com/hoangmirs/go-scraper/issues/5

## What happened 👀

Describe the big picture of your changes here to communicate to the team why we should accept this pull request.

## Insight 📝

Describe in details how to test the changes, which solution you tried but did not go with, referenced documentation is welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, gif, etc.

2021-01-25 10:55 UTC, olivierobert commented on assets/stylesheets/screens/_session.scss
> +  }
Missing blank link. Make the code breadth 🌬️

2021-01-25 10:55 UTC, olivierobert commented on assets/stylesheets/screens/_session.scss
> +  .session-card {
Prefer using the component as prefix

```suggestion
  .card-session {
```

The same applied below for `form-session

Please refer to Compass:
> Use the UI element type as a prefix following by one to two words. While it might seem counter-intuitive at first, this technique makes it easier to differentiate component purpose and search through components. Most framework use this technique e.g. btn-primary is not called primary-btn as btn is the namespace grouping all buttons.
> https://nimblehq.co/compass/development/code-conventions/css/#class-names

2021-01-25 10:55 UTC, olivierobert commented on controllers/default.go
> +	}
Not sure if it's a best practice in Beego but I can predict this might get repetitive to add this to add controllers. What do you think about moving this to a middleware later on? I found [this example code](https://github.com/ojardila/beego_middleware/blob/master/middleware.go). In Gin, that's the default implementation path as you can see on Gut's IC: https://github.com/gutakk/go-google-scraper/tree/development/middlewares

Maybe, having a flag in the controller struct and check on this in `baseController` might also be sufficient:

```
type MainController struct {
	baseController
    requireAuthenticatedUser bool
}
```

2021-01-25 10:55 UTC, olivierobert commented on controllers/default.go
> +	web.ReadFromRequest(&c.Controller)
What is `ReadFromRequest` for?

2021-01-25 10:55 UTC, olivierobert commented on forms/session_test.go
> +					Expect(user).NotTo(BeNil())
How about asserting on the actual user struct or at least user ID to make sure it's the current user. Also having back to back asserting on Nil is kind of hard to read 😵

2021-01-25 10:55 UTC, olivierobert commented on forms/session_test.go
> +					Expect(err.Error()).To(Equal("Email can not be empty"))
Minor thing but I notice you tend to use `can not` while `cannot` is the preferred format. Grammarly as reference: https://www.grammarly.com/blog/cannot-or-can-not/

You can check this out on all code later on too 😁

2021-01-27 06:48 UTC, gutakk commented on assets/stylesheets/layouts/index.scss
> +@import './application';
Should this be `@import './_application';`? If yes please check another import too.

2021-01-27 06:48 UTC, gutakk commented on controllers/session.go
> +	"github.com/hoangmirs/go-scraper/forms"
How about grouping the import?

2021-01-27 06:48 UTC, gutakk commented on controllers/session.go
> +	if c.CurrentUser != nil {
Same as @olivierobert comments. This will be used in so many places.

2021-01-27 06:48 UTC, gutakk commented on controllers/session.go
> +	_ = c.ParseForm(&sessionForm)
Regarding to our convention, we should handle all the errors.

2021-01-27 06:48 UTC, gutakk commented on controllers/session_test.go
> +			request, _ := http.NewRequest("GET", "/login", nil)
We should to handle all the errors in the test file too. You can do something like what Pae [done](https://github.com/carryall/go-google-scraper-challenge/blob/chore/chore-3-setup-test/helpers/test/controller.go#L16-L23).

Also, I saw most of the controller tests have following lines of code
```go
request, _ := http.NewRequest("GET", "/login", nil)
response := httptest.NewRecorder()
web.BeeApp.Handlers.ServeHTTP(response, request)
```

How about moving this to something like helper function for test?

2021-01-27 06:48 UTC, gutakk commented on controllers/session_test.go
> +				_, _ = registrationForm.CreateUser()
IMO, as this is the login test, I prefer to insert user to database directly instead of using registrationForm to make the test isolated.

You can see Pae solution [here](https://github.com/carryall/go-google-scraper-challenge/blob/chore/chore-3-setup-test/helpers/test/model.go#L10-L17). I think this is the good way to go.

What do you think?

2021-01-27 06:48 UTC, gutakk commented on forms/session.go
> +	"github.com/hoangmirs/go-scraper/helpers"
How about group the import?

2021-02-03 05:09 UTC, hoangmirs commented on controllers/session_test.go
> +				_, _ = registrationForm.CreateUser()
I tried doing it like that, but something went wrong with it, so I got some weird errors. I will try refactoring it later

2021-02-03 07:05 UTC, hoangmirs commented on assets/stylesheets/layouts/index.scss
> +@import './application';
`@import './application';` and `@import './_application';` are the same, I'm not sure, but my VSCode auto-completion suggest to use `@import './application';`. I also found this example:
https://sass-lang.com/documentation/at-rules/import#index-files

2021-02-03 08:43 UTC, olivierobert requested changes
Nice to see a non-middleware implementation for user checks 💪 However I recommend some improvements.

2021-02-03 08:43 UTC, olivierobert commented on controllers/base.go
> +	c.SetCurrentUser(user)
I agree with Gut that it's an unexpected side effect of this method. So there could be a method to perform the check for a guest user and an authenticated user. So instead of doing `!reflect.ValueOf(c.Data["CurrentUser"]).IsZero()`, prefer having a method with more logic into it:

```go
if c.requireGuestUser && ensureGuestUser() {
  c.Ctx.Redirect(http.StatusFound, "/")
}
```

2021-02-03 11:05 UTC, gutakk commented on assets/stylesheets/layouts/index.scss
> +@import './application';
Yes It is the same but according to our [convention](https://nimblehq.co/compass/development/code-conventions/css/#files) it should be `@import './_application';`

2021-02-03 11:07 UTC, gutakk commented on controllers/session_test.go
> +				_, _ = registrationForm.CreateUser()
It's ok to separate to another task if you want 😁

2021-02-03 11:26 UTC, hoangmirs commented on controllers/base.go
> +	c.SetCurrentUser(user)
I created 2 methods to refactor this, please help me check again @olivierobert

2021-02-05 08:16 UTC, olivierobert approved these changes

2021-02-08 03:36 UTC, gutakk approved these changes

2021-02-08 03:37 UTC, merged