[Frontend] As a user, I can upload a CSV file and check the result
hoangmirs/go-scraper pull request #42
Opened 2021-03-08 10:36 UTC by hoangmirs

Resolve #33 

## What happened 👀

Create UI to upload CSV file

## Insight 📝

N/A

## Proof Of Work 📹

![2021-03-08 17 33 29](https://user-images.githubusercontent.com/7344405/110310056-ab911980-8034-11eb-9370-15a0cd7dbc11.gif)

2021-03-09 08:15 UTC, hoangmirs commented on assets/stylesheets/screens/_keyword.scss
> +.keyword.post {
Thanks, I changed in https://github.com/hoangmirs/go-scraper/pull/42/commits/81d58e76023200f1133ee9c384166a4f892f19bb

2021-03-10 08:42 UTC, olivierobert requested changes

2021-03-10 08:42 UTC, olivierobert commented on views/keyword/index.html
> +      class="form keyword-upload-form"
The class name should be:

```suggestion
      class="form form-keyword-upload"
```

From [Compass](https://nimblehq.co/compass/development/code-conventions/css/):

> Use the UI element type as a prefix following by one to two words.

2021-03-10 08:42 UTC, olivierobert commented on views/keyword/index.html
> +<div class="keyword-main">
This looks like a hack 🙈 It seems something that should be managed at the layout levl so that it can be reused on multiple screens.

2021-03-12 07:38 UTC, olivierobert approved these changes

2021-03-12 08:16 UTC, Lahphim approved these changes

2021-03-14 14:15 UTC, merged